"""migration for User and other tables

Revision ID: 9a1e7ca54619
Revises: 
Create Date: 2024-11-03 11:43:07.761332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1e7ca54619'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('about', sa.String(length=250), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('passwd', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users')
    with op.batch_alter_table('actor_types', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.CHAR(length=2),
               type_=sa.String(),
               nullable=False)

    with op.batch_alter_table('event_types', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('actor_type_code',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('industry_code',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('motive_code',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('event_type_code',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('country_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=True)
        batch_op.create_foreign_key(None, 'countries', ['country_code'], ['code'])

    with op.batch_alter_table('industries', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('motives', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motives', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('industries', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('country_code',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('event_type_code',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('motive_code',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('industry_code',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('actor_type_code',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('event_types', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.String(),
               type_=sa.CHAR(length=2),
               nullable=True)

    with op.batch_alter_table('actor_types', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('about', sa.VARCHAR(), nullable=True),
    sa.Column('admin', sa.INTEGER(), nullable=True),
    sa.Column('passwd', sa.NUMERIC(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###
