@startuml usecase

left to right direction

:User: 
:Admin: 

User <|-- Admin

package "Incidents" {
    :User: --> (signs up)
    :User: --> (logs in)
    :User: --> (searches incidents)
    :User: --> (lists incidents)
    :Admin: --> (creates an incident)
    :Admin: --> (updates an incident)
    :Admin: --> (deletes an incident)
    :User: --> (generates a report of incidents)
@enduml